### ISSUE TITLE
Thoughts on my styling approach

### ISSUE THREAD

**Issue by renshenhe** [mxstbr/ama#22]
I have been experimenting with using a mix of css and inline-styles for creating reusable components and a personal ui which I hope to open source should I find it feasible.  

In my case though I have restricted globally accessible CSS to layout(maintaining  container sizes and responsive) primarily grid system with prefixes like `qp-grid` , `qp-cell--col-6`, and `qp-cell--6-col-tablet` as a bandaid to namespace collision.

Component css is used for all static styles and encapsulated with css modules while leaving all customizable styles and animation inline like so:

SomeComponent.js
```js
<div
  className='qp-component'
  style={{
      width: `${width}px`,
      transform: isOpen 
        ? `translate3d(0px, 0px, 0px)`
        : `translate3d(-${width + 10}px, 0px, 0px)`,
      backgroundColor: backgroundColor,
      transition: isOpen 
        ? 'transform 200ms cubic-bezier(0.4, 0, 0.6, 1)'
        : 'transform 200ms cubic-bezier(0, 0, 0.2, 1)'
  }}
/>

```

component.css
```css
.qp-component {
  top: 0;
  left: 0;
  bottom: 0;
  position: fixed;
  z-index: 5;
  overflow-x: hidden;
  overflow-y: auto;
  box-shadow: 0 16px 24px 2px rgba(0, 0, 0, 0.14), 0 6px 30px 5px rgba(0, 0, 0, 0.12), 0 8px 10px -5px rgba(0, 0, 0, 0.2);
}
```

This approach
- Reduces the amount of bloat injected into the dom from overload of inline styles especially in cases where large quantities of an item is rendered.
- Reduces overall js file size
- Allows css to be cached
- Allow component to be customized to a certain extent (possibly by passing a destructured style prop or just restricting certain styles to be replaced) without creating/adding another class.
- ? Reduce reconciliation checks on styles that are static

I have adopted web animations api instead of using keyframes and deal with pseudo-selectors using react's event system with the exception of child selectors.

From your experience dealing with react and styling I would be pleased to hear your opinion/critique on this approach.

Thanks and I enjoyed your talks, hope there's more in 2017!
